---
title: "Pmweb Report"
author: "Paulo Souza Junior"
date: "January 23, 2018"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Introdução

Este documento apresenta ...


## Estrutura

```{r acidentes}
require("dplyr")
require("ggplot2")
require(scales)

setwd("~/Documents/pmweb") #Necessário adicionar path onde os arquivos estão
fNames <- list.files(pattern = "acidentes-2*")


acidentes <- lapply(fNames, function(fNames){
  data.frame(read.csv(fNames, header=TRUE, sep=";"))
})

test <- data.frame(acidentes[[1]])

test <- select(test, DATA_HORA, TEMPO, UPS)

test$ano <- 2000

test2 <- data.frame(acidentes[[2]])

test2 <- select(test2, DATA_HORA, TEMPO, UPS)

test2$ano <- 2001

test3 <- rbind(test, test2)

ggplot(test3, aes(x = as.POSIXct(format(strptime(DATA_HORA, "%Y%m%d %H:%M"), format='%H:%M'), format="%H:%M"), y = UPS, colour=TEMPO)) + geom_jitter() + labs(x="Hora") + scale_x_datetime(date_breaks = "2 hour",
                       date_labels = "%H:%M") + facet_wrap(~ano)

```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
